engines:
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCaseVariableName:
        enabled: false
      Controversial/CamelCaseParameterName:
        enabled: false
      Naming/LongVariable:
        enabled: false
exclude_paths:
  - tests/**/*
  - vendor/**/*
ratings:
  paths:
    - "**.php"
    - "**.module"
    - "**.inc"