engines:
  phpcodesniffer:
    enabled: true
    checks:
      PSR2 Classes PropertyDeclaration Underscore:
        enabled: false
      PSR2 Methods MethodDeclaration Underscore:
        enabled: false
  phpmd:
    enabled: true
    config:
        file_extensions: "php"
        rulesets: "codesize,design,unusedcode"
exclude_paths:
  - "tests/**/*"
  - "vendor/**/*"
ratings:
  paths:
    - "**.php"
    - "**.module"
