build:
    environment:
        php:
            version: 5.6.9
    dependencies:
            override:
                - composer install --dev --no-progress --no-interaction
build:
    tests:
        override:
            -
                command: phpunit --coverage-clover=my-coverage-file
                coverage:
                    file: my-coverage-file
                    format: php-clover
filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php: {  }