build:
    environment:
        php:
            version: 5.6.9
    dependencies:
            override:
                - composer install --dev --no-progress --no-interaction
    tests:
        override:
            -
                command: phpunit --coverage-clover=build/logs/clover.xml --process-isolation
                coverage:
                    file: build/logs/clover.xml
                    format: php-clover
filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php: {  }