build:
    environment:
        php:
            version: 5.6.9
    dependencies:
            override:
                - composer install --dev --no-progress --no-interaction
filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php: {  }