language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - composer install --ignore-platform-reqs
  - phpunit --process-isolation