language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres -d travis_ci_test -f examples/example.sql
  - composer install --ignore-platform-reqs --no-progress
  - phpunit --process-isolation